{{- $orgNum := int $.Values.orgNum -}}
{{- range $loopIndex, $caIndex := untilStep 1 (int (add $orgNum 1)) 1 }}
{{- $caFullName := (printf "%s-ca%d" $.Values.fabricNetwork $caIndex) }}
kind: Service
apiVersion: v1
metadata:
  name: {{ $caFullName }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ $caFullName }}
  ports:
    - protocol: TCP
      port: 7054
      targetPort: 7054
      name: ca-port
---
{{- end }}
