apiVersion: v1
kind: Pod
metadata:
  name: fabric-init-pod
  labels:
    app: fabric-init
spec:
  containers:
    - name: fabric-init
      image: hyperledger/fabric-tools:x86_64-{{ $.Values.hyperledgerFabricVersion }}
      imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
      env:
        - name: FABRIC_CHANNEL
          value: {{ .Values.fabricChannel | quote }}
      command: ["/var/hyperledger/production/config/fabric-init.sh"]
      volumeMounts:
        - name: fabric-network-root
          mountPath: /var/hyperledger/production
      readinessProbe:
        exec:
          command:
          - ls
          - /var/hyperledger/production/INIT-COMPLETED
        initialDelaySeconds: 2
        periodSeconds: 2
  initContainers:
    - name: check-generator
      image: hyperledger/fabric-tools:x86_64-{{ $.Values.hyperledgerFabricVersion }}
      imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
      command: ['sh', '-c', 'sleep 2; until [ -f /var/hyperledger/production/GENERATION-COMPLETED ]; do echo waiting for fabric-network-generator; sleep 2; done; sleep 2;']
      volumeMounts:
        - name: fabric-network-root
          mountPath: /var/hyperledger/production
          readOnly: true
  volumes:
    - name: fabric-network-root
      hostPath:
        path: /data/fabric/{{ $.Values.fabricNetwork }}/
        # Below type field is necessary to avoid auto creation of dir if not present during init container check
        # type: Directory
