apiVersion: v1
kind: Pod
metadata:
  name: fabric-utils-pod
  labels:
    app: fabric-utils
spec:
  containers:
    - name: fabric-utils
      image: registry.cn-hangzhou.aliyuncs.com/cos-solution/fabric-utils:latest
      imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
      tty: true
  
